# Generated by Django 5.0.6 on 2024-07-05 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instuctions',
            new_name='Ingredient',
        ),
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Instuction',
        ),
    ]
