# Generated by Django 5.0.6 on 2024-07-05 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_recipe_ingredients_alter_recipe_instructions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='instructions',
        ),
    ]
