# Generated by Django 5.0.6 on 2024-07-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_recipe_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author_id',
            field=models.CharField(default='admin', max_length=100),
            preserve_default=False,
        ),
    ]
