# Generated by Django 5.0.6 on 2024-07-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_alter_recipe_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instuction',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='recipe.ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
