# Generated by Django 5.0.6 on 2024-07-05 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0013_rename_user_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
