# Generated by Django 5.0.6 on 2024-07-05 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0015_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
    ]
