# Generated by Django 5.0.6 on 2024-07-05 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0016_rename_author_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='commented_by',
        ),
    ]
