# Generated by Django 5.0.6 on 2024-07-07 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0021_remove_recipe_ingredients_recipe_ingredients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
