# Generated by Django 5.0.6 on 2024-07-07 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0022_delete_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commented_by',
        ),
    ]
