version: '3.8'

services:
  django:
   container_name: django
   build:
    context: ./tastebuds
   command: python manage.py runserver 0.0.0.0:8000
   volumes:
    - ./tastebuds:/usr/src/app
   ports:
    - '8000:8000'
   environment:
    - DEBUG=1
    - SECRET_KEY=rttyrhuirhtr84055u
    - ALLOWED_HOSTS=*

  pgdb:
   container_name: pgdb
   image: postgres
   restart: always
   ports:
     - "5432:5432"
   environment:
     - POSTGRES_DB=postgres
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     